
sudo: 'required'

services:
  - 'docker'

script:
  - docker build -t $IMAGE .

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $IMAGE

notifications:
  email: false