
sudo: 'required'

services:
  - 'docker'

script:
  - docker build -t $IMAGE_AMD64 .

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $IMAGE_AMD64

notifications:
  email: false