
 
sudo: 'required'

services:
  - 'docker'

script:
  - docker build -t $IMAGE .

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker push $IMAGE
    fi

notifications:
  email: false